name: nyt-crossword-to-kindle

services:
  sender:
    container_name: crossword-sender
    image: nyt-crossword-to-kindle:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ${CROSSWORD_DOWNLOADS_PATH}:/crosswords/downloads
      - ${NYT_COOKIES_PATH}:/crosswords/cookies.nyt.txt
      # To allow for changing .env without restarting the container
      - ./.env:/crosswords/.env
