name: nyt-crossword-to-kindle

services:
  sender:
    container_name: crossword-sender
    image: nyt-crossword-to-kindle:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ${DOWNLOADS_SYSTEM_PATH}:/crosswords/downloads
      - ${COOKIE_FILE}:/crosswords/cookies.nyt.txt
    command: "${CROSSWORD_COMMAND_LINE_ARGUMENTS}"