name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  check-for-cc:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title and Body
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
  check-tag:
    name: Check for New Tag
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: [check-for-cc]
    if: needs.check-for-cc.result == 'success'
    steps:
    - name: Checkout Code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        fetch-depth: 0
    - id: ccv
      name: Tag Increment Generator
      uses: smlx/ccv@7318e2f25a52dcd550e75384b84983973251a1f8 # v0.10.0
      with:
        write-tag: false
    - name: Visualise Incremented Tag
      env:
        NEW_TAG: ${{ steps.ccv.outputs.new-tag }}
        NEW_TAG_VERSION: ${{ steps.ccv.outputs.new-tag-version }}
        NEW_TAG_VERSION_TYPE: ${{ steps.ccv.outputs.new-tag-version-type }}
      run: |
        echo "new-tag=${NEW_TAG}"
        echo "new-tag-version=${NEW_TAG_VERSION}"
        echo "new-tag-version-type=${NEW_TAG_VERSION_TYPE}"
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 #v3.11.1
      # Optional: Login to Docker Hub if pushing images
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Preview Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          context: .
          push: false
          #tags: user/app:latest